top_srcdir   = /home/osnapdev/UO-CIS322/httpd-2.4.25
top_builddir = /home/osnapdev/UO-CIS322/httpd-2.4.25
srcdir       = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/dav/lock
builddir     = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/dav/lock
VPATH        = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
