top_srcdir   = /home/osnapdev/UO-CIS322/httpd-2.4.25
top_builddir = /home/osnapdev/UO-CIS322/httpd-2.4.25
srcdir       = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/arch/unix
builddir     = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/arch/unix
VPATH        = /home/osnapdev/UO-CIS322/httpd-2.4.25/modules/arch/unix

include $(top_srcdir)/build/special.mk

