import app.views.add_asset
import app.views.add_facility
import app.views.asset_report
import app.views.create_user
import app.views.dashboard
import app.views.dispose_asset
import app.views.index
import app.views.login
import app.views.logout
import app.views.transfer_request
